# This workflow will do a clean installation of node dependencies, cache/restore them, run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Convert xml to json

on:
  push:
    branches: 
    - tabelaxml

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]
    
    defaults:
      run:
        working-directory: ./itunes-xml-to-json

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: install dependences
      run: npm i
    
    - name: run xml-to-json-file
      run: npm start

    - name: create-json
      uses: jsdaniell/create-json@v1.2.2
      with:
        name: "new-json-file.json"
        json: '{"name":"jsdaniell", "password":"mypass"}'
        dir: ./itunes-xml-to-json
    - run: git config --global user.email "juliabraga@gmail.com" && git config --global user.name "juliabraga" && git add . && git add --force src/devdatatools-firebase-adminsdk.json && git status && git commit -a -m "JSON created!"
